name: Generate build

on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Get Zircolite repository
        shell: bash
        run: |
          git clone https://github.com/wagga40/Zircolite.git
          cp -r ./Zircolite/* .
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt -r requirements.full.txt

      - name: Get Zircolite version
        if: runner.os == 'Windows'
        run: |
          $Version = (Select-String -Path .\zircolite.py -Pattern 'version = "' | Select-Object -ExpandProperty line | Out-String).Split('"')[1]
          echo "ZIRCOLITE_VERSION=$Version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: zircolite.py
          onefile: true
          enable-plugins: multiprocessing
          windows-icon-from-ico: ./build/app.ico
          product-name: Zircolite
          file-version: ${{ env.ZIRCOLITE_VERSION }}
          product-version: ${{ env.ZIRCOLITE_VERSION }}
          company-name: Wagga
          file-description: Zircolite
          copyright: Wagga

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
